[project]
name = soter2_natpunch
version = 0.0.1

[files]
sources = *.c
output = natpunch

[dirs]
includes = include ../lownet/include
libs = ../lownet/lib
src = src
output = lib

[compiler]
build = static
cleanup = false

[dependencies]
libs = ../lownet/lib/*

[modules]
lnet = ../lownet, abs.conf

[flags]
common = -std=c11 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g  -O0

[mode.release]
flags = -O3

