[project]
name = soter2_provide
version = 0.0.1

[files]
sources = *.c
output = provide

[dirs]
includes = include  ../lownet/include ../base/include ../protocol/include
src = src
output = lib

[compiler]
build = static
cleanup = false

[modules]
lnet   = ../lownet, abs.conf
base   = ../base, abs.conf
proto  = ../protocol, abs.conf

[flags]
common = -std=c23 -Wall -Wextra -Wpedantic

[modes]
active = debug

[mode.debug]
flags = -g -O1 -D_GNU_SOURCE

