[project]
name = soter2_onion
version = 0.0.1

[files]
sources = *.c
output = onion

[dirs]
includes = include ../protocol/include ../lownet/include ../base/include ../providers/include ../peersyst/include ../rudp/include ../e2ee/include ../gossip/include ../crypto/include
src = src
output = lib

[compiler]
build = static
cleanup = false

[modules]
providers = ../providers, abs.conf

[flags]
common = -std=c11 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g  -O0

[mode.release]
flags = -O3
