[project]
name = soter2_peersyst
version = 0.0.1

[files]
sources = *.c
output = peersyst

[dirs]
includes = include ../base/include ../lownet/include ../crypto/include
src = src
output = lib

[modules]
base = ../base, abs.conf
lnet = ../lownet, abs.conf

[compiler]
build = static
cleanup = false

[flags]
common = -std=c11 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g  -O0

[mode.release]
flags = -O3

