[project]
name = soter2_base
version = 0.0.1

[files]
sources = **/*.c *.c
output = base

[dirs]
includes = include
src = src
output = lib

[compiler]
build = static
cleanup = false

[flags]
common = -std=c11 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g -O1

