[project]
name = soter2_turn
version = 0.0.1

[files]
sources = *.c
output = turn

[dirs]
includes = include ../crypto/include ../lownet/include ../base/include ../protocol/include ../peersyst/include
src = src
output = lib

[compiler]
build = static

[modules]
crypto = ../crypto, abs.conf
lnet   = ../lownet, abs.conf

[flags]
common = -std=c11 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g  -O0

[mode.release]
flags = -O3
