[project]
name = soter2_logging
version = 0.0.1

[files]
sources = logging.c
output = logging

[dirs]
includes = include
src = src
output = lib

[compiler]
build = static
cleanup = false

[flags]
common = -std=c23 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g -fsanitize=address -O0

[mode.release]
flags = -O3


