[project]
name = soter2_logging
version = 0.0.1

[files]
sources = logging.c
output = logging

[dirs]
includes = include
src = src
output = lib

[compiler]
build = static

[flags]
common = -std=c11 -Wall -Wextra -Wpedantic

