[project]
name = soter2_interface
version = 0.0.1

[files]
sources = *.c
output = interface

[compiler]
build = static
cleanup = false

[dirs]
output = lib
includes = include ../e2ee/include ../providers/include ../peersyst/include ../rudp/include ../stating/include ../gossip/include ../natpunch/include ../watcher/include ../protocol/include ../lownet/include ../crypto/include ../logging/include ../base/include
src = src

[flags]
common = -std=c23 -Wall -Wextra -Wpedantic

[modes]
active = debug

[mode.debug]
flags = -g -O3 -D_GNU_SOURCE