[project]
name = soter2_stating
version = 0.0.1

[files]
sources = *.c
output = stating

[dirs]
includes = include ../crypto/include ../lownet/include
libs = ../crypto/lib ../lownet/lib
src = src
output = lib

[compiler]
build = static

[dependencies]
libs = ../crypto/lib/* ../lownet/lib/*

[modules]
crypto = ../crypto, abs.conf
lnet   = ../lownet, abs.conf

[flags]
common = -std=c23 -Wall -Wextra -Wpedantic

[modes]
active = debug

[mode.debug]
flags = -g -O1 -D_GNU_SOURCE

