[project]
name = soter2_stating
version = 0.0.1

[files]
sources = *.c
output = stating

[dirs]
includes = include ../crypto/include ../lownet/include ../base/include
src = src
output = lib

[compiler]
build = static

[modules]
crypto = ../crypto, abs.conf
lnet   = ../lownet, abs.conf

[flags]
common = -std=c23 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g -O0

