[project]
name = soter2_socks5_server
version = 0.0.1

[files]
sources = socks5_test.c
output = socks5

[compiler]
cc = gcc

[dependencies]
libs = ../devcore/interface/lib/* ../devcore/proxy/lib/* ../devcore/quic/lib/* ../devcore/turn/lib/* ../devcore/e2ee/lib/* ../devcore/providers/lib/* ../devcore/peersyst/lib/* ../devcore/rudp/lib/* ../devcore/stating/lib/* ../devcore/gossip/lib/* ../devcore/natpunch/lib/* ../devcore/watcher/lib/* ../devcore/protocol/lib/* ../devcore/lownet/lib/* ../devcore/crypto/lib/* ../devcore/logging/lib/* ../devcore/base/lib/* sodium picoquic-core picotls-fusion picoquic-log picotls-core picotls-minicrypto picotls-openssl crypto

[dirs]
libs = ../devcore/**/lib
output = bin
includes = include ../devcore/**/include
src = src

[flags]
common = -std=c11 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g -O0

[mode.release]
flags = -O3
