[project]
name = soter2_gossip
version = 0.0.1

[files]
sources = *.c
output = gossip

[dirs]
includes = include ../base/include ../protocol/include
src = src
output = lib

[modules]
base = ../base, abs.conf
proto= ../protocol, abs.conf

[compiler]
build = static
cleanup = false

[flags]
common = -std=c23 -Wall -Wextra -Wpedantic

[modes]
active = debug

[mode.debug]
flags = -g -O3 -D_GNU_SOURCE
