[project]
name = soter2_rele
version = 0.0.1

[files]
sources = *.c
output = rele

[dirs]
includes = include ../protocol/include ../lownet/include ../base/include ../providers/include
src = src
output = lib

[compiler]
build = static
cleanup = false

[modules]
providers = ../providers, abs.conf

[flags]
common = -std=c23 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g  -O0

[mode.release]
flags = -O3

