[project]
name = soter2_cli
version = 0.0.1

[files]
sources = *.c
output = soter

[compiler]
cc = gcc

[dependencies]
libs = ../devcore/interface/lib/* ../devcore/rele/lib/* ../devcore/e2ee/lib/* ../devcore/providers/lib/* ../devcore/peersyst/lib/* ../devcore/rudp/lib/* ../devcore/stating/lib/* ../devcore/gossip/lib/* ../devcore/natpunch/lib/* ../devcore/watcher/lib/* ../devcore/protocol/lib/* ../devcore/lownet/lib/* ../devcore/crypto/lib/* ../devcore/logging/lib/* ../devcore/base/lib/* sodium

[dirs]
libs = ../devcore/**/lib
output = bin
includes = include ../devcore/**/include
src = src

[modules]
devcore = ../devcore, abs.conf

[flags]
common = -std=c23 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g  -O0

[mode.release]
flags = -O3