[project]
name = soter2_watcher
version = 0.0.1

[files]
sources = *.c
output = watcher

[dirs]
includes = include ../providers/include ../lownet/include ../base/include ../protocol/include
src = src
output = lib

[modules]
lownet   = ../lownet, abs.conf
provider = ../providers, abs.conf
base     = ../base, abs.conf
protocol = ../protocol, abs.conf

[compiler]
build = static
cleanup = false

[flags]
common = -std=c23 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g -O0

