[project]
name = soter2_main
version = 0.0.1

[files]
sources = main.c
output = main

[compiler]
cc = gcc

[dirs]
libs = ../devcore/**/lib
output = bin
includes = ../devcore/**/include 

[flags]
common = -std=c11 -Wall -Wextra -Wpedantic

