[project]
name = soter2_crypto
version = 0.0.1

[files]
sources = *.c
output = ucrypto

[dirs]
includes = include
src = src
output = lib

[compiler]
build = static
cleanup = false

[dependencies]
libs = sodium

[flags]
common = -std=c23 -Wall -Wextra -Wpedantic

[modes]
active = debug

[mode.debug]
flags = -g -O3 -D_GNU_SOURCE

