[project]
name = soter2_crypto
version = 0.0.1

[files]
sources = *.c
output = ucrypto

[dirs]
includes = include
src = src
output = lib

[compiler]
build = static
cleanup = false

[dependencies]
libs = sodium

[flags]
common = -std=c11 -Wall -Wextra -Wpedantic -D_GNU_SOURCE

[modes]
active = debug

[mode.debug]
flags = -g  -O0

[mode.release]
flags = -O3

