[project]
name = soter2_devcore
version = 0.0.1

[modules]
base      = base, abs.conf
crypto    = crypto, abs.conf
gossip    = gossip, abs.conf
logging   = logging, abs.conf
lownet    = lownet, abs.conf
natpunch  = natpunch, abs.conf
peersyst  = peersyst, abs.conf
protocol  = protocol, abs.conf
providers = providers, abs.conf
rudp      = rudp, abs.conf
stating   = stating, abs.conf
watcher   = watcher, abs.conf
e2ee      = e2ee, abs.conf
onion     = onion, abs.conf
interface = interface, abs.conf
