[project]
name = soter2_e2ee
version = 0.0.1

[files]
sources = *.c
output = e2ee

[dirs]
includes = include ../base/include ../protocol/include ../rudp/include ../crypto/include ../lownet/include ../providers/include
src = src
output = lib

[compiler]
build = static
cleanup = false

[flags]
common = -std=c23 -Wall -Wextra -Wpedantic

[modes]
active = debug

[mode.debug]
flags = -g -O3 -D_GNU_SOURCE
